---
- name: "stop cert-update"
  systemd:
    state: stopped
    daemon_reload: yes
    name: certificate-update
- name: certificate-update
  file: src=certificate-update.service dest=/etc/systemd/system/certificate-update2.service owner=root group=root mode=0755
- name: docker-compose for letsencrypt
  file: src=docker-compose.yaml dest=/data/nginx
  notify:
    - reload systemctl
- name: certificate-update
  service: name=certificate-update2.service state=started enabled=yes