# Default policy
- iptables:
    chain: INPUT
    policy: ACCEPT
    comment: allow all icoming acept Docker and SSH 

- iptables:
    chain: FORWARD
    policy: ACCEPT
    comment: ALLOW all outgoing

- iptables:
    chain: OUTPUT
    policy: ACCEPT
    comment: ALLOW all outgoing

- iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
    comment: allows inbound SSH
    action: insert
    rule_num: 1


- iptables:
    chain: INPUT
    state: present
    jump: ACCEPT
    comment: allow RELATED,ESTABLISHED

#- iptables:
#    chain: INPUT
#    policy: DROP
#    comment: DENY all icoming acept Docker and SSH 


