---
- name: certificate-update.timer
  template: 
    src: certificate-update.timer.j2
    dest: /etc/systemd/system/certificate-update.timer
  notify:
    - reload systemctl
- name: certificate-update
  service: name=certificate-update.timer state=started enabled=yes daemon_reload=yes