---
- name: check if lcp folder exists
  stat: 
    path: /opt/{{ inventory_hostname }}/backend/
  register: lcp_folder

- name: Install epel-release
  package:
    name: epel-release
    state: present
  when: lcp_folder.stat.exists == false and lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Install a base packages
  package:
    name:
      - sudo
      - yum-utils
      - htop
      - nano 
      - mc
      - vim
      - nmap
      - wget
      - iptables-services
#      - python-docker-py
    state: present
  when: lcp_folder.stat.exists == false and lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Add groups
  group:
    name: aimc
    state: present
  when: lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Sudo access
  copy:
    content: >-
      # aimc team

      %aimc ALL=(ALL) NOPASSWD:ALL

    dest: /etc/sudoers.d/10-aimc-users
    owner: root
    group: root
    mode: 0440
  when: lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Add team member
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: aimc
    append: yes
  with_items: "{{ teams.aimc.members }}"
  when: lookup('env', 'LOCAL_DEPLOY') != "true"
  ignore_errors: True
- name: Set authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  with_items: "{{ teams.aimc.members }}"
  when: lookup('env', 'LOCAL_DEPLOY') != "true"
  ignore_errors: True

- name: Create docker group
  group:
    name: "docker"
    state: present
  when: lcp_folder.stat.exists == false and lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Set hostname
  shell: hostnamectl set-hostname freeipa.aimc.io
  when: lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
  when: lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Add jounald rotation rule
  lineinfile:
    path: /etc/systemd/journald.conf
    line: SystemMaxUse=1g
  when: lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Add docker images prune command to crontab
  lineinfile:
    path: /etc/crontab
    line: 0 3 * * SUN root /bin/docker system prune --volumes -a -f
  when: lookup('env', 'LOCAL_DEPLOY') != "true"

- name: Copy syslog logrotate configuration
  template:
    src: ./templates/configs/logrotate_syslog.j2
    dest: "/etc/logrotate.d/syslog"
  when: lookup('env', 'LOCAL_DEPLOY') != "true"

